image: christiantragesser/dind-ci

variables:
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind

stages:
  - test

test:
  stage: test
  tags:
    - docker
  script:
    - pytest $CI_PROJECT_DIR/test
