variables:
  IMAGE_NAME: aws-access-key-manager

include:
  - project: christiantragesser/gitlab-ci-templates
    ref: master
    file:
      - goreleaser.yml
      - kaniko.yml

stages:
  - publish
  - release

.default_branch_only:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - go.*
        - main.go
        - utils/*
        - pkg/Dockerfile.pipeline

publish:binary:
  stage: publish
  extends:
    - .bin_publish
    - .default_branch_only
  artifacts:
    paths:
      - dist/aws-access-key-manager_linux_amd64/aws-access-key-manager-linux-amd64

publish:container:
  stage: publish
  needs: ["publish:binary"]
  extends:
    - .kaniko_publish
    - .default_branch_only
  variables:
    DOCKERFILE_PATH: ./pkg/Dockerfile.pipeline
    DOCKER_BUILD_STAGE: publish
  dependencies:
    - publish:binary

release:github:
  stage: release
  extends:
    - .gh_release

release:container:
  stage: release
  extends:
    - .kaniko_release
