variables:
  IMAGE_NAME: aws-access-key-manager
  IMAGE_FILE_PATH: $CI_PROJECT_DIR

include:
  - project: christiantragesser/gitlab-ci-templates
    ref: master
    file:
      - kaniko.yml

stages:
  - publish

publish:
  stage: publish
  tags:
    - docker
  extends:
    - .kaniko
  variables:
    DOCKER_BUILD_STAGE: publish
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - go.mod
        - main.go
        - utils/*
        - Dockerfile